<a href="https://colab.research.google.com/github/Mumthaz-Alfan/ICT-ACTIVITY/blob/main/numpyactivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


arr1 = np.arange(10, 50)
print("Original Array:\n", arr1)


matrix_4x10 = arr1.reshape(4, 10)
print("\nReshaped 4x10 Matrix:\n", matrix_4x10)


last_column = matrix_4x10[:, -1]
print("\nLast Column:\n", last_column)

Original Array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reshaped 4x10 Matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last Column:
 [19 29 39 49]


In [2]:
import numpy as np

# 1. Create the two 3x3 matrices
matrix_fives = np.full((3, 3), 5)
matrix_1to9 = np.arange(1, 10).reshape(3, 3)

print("Matrix of 5s:\n", matrix_fives)
print("\nMatrix of 1 to 9:\n", matrix_1to9)

# 2. Add the two matrices
added_matrix = matrix_fives + matrix_1to9
print("\nAdded Matrices:\n", added_matrix)

# 3. Multiply them element-wise
multiplied_matrix = matrix_fives * matrix_1to9
print("\nElement-wise Multiplied Matrices:\n", multiplied_matrix)

# 4. Find the transpose of the multiplied result
transposed_matrix = multiplied_matrix.T
print("\nTranspose of Multiplied Result:\n", transposed_matrix)

Matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix of 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Added Matrices:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplied Matrices:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of Multiplied Result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
import numpy as np

# 1.  an array of 15 random integers between 10 and 100
# (Note: high=101 because the upper bound is exclusive in np.random.randint)
random_arr = np.random.randint(10, 101, size=15)
print("Original Random Array:\n", random_arr)

# 2. Count how many values are greater than 50 before replacing them
replaced_count = np.sum(random_arr > 50)

# 3. Replace all values greater than 50 with -1
random_arr[random_arr > 50] = -1

print("\nModified Array (values > 50 replaced with -1):\n", random_arr)
print(f"\nNumber of values replaced: {replaced_count}")

Original Random Array:
 [83 26 41 88 81 24 73 79 39 62 21 53 42 64 16]

Modified Array (values > 50 replaced with -1):
 [-1 26 41 -1 -1 24 -1 -1 39 -1 21 -1 42 -1 16]

Number of values replaced: 8


In [4]:
import numpy as np

# 1. A 5x4 array with random values between 0 and 1
rand_arr = np.random.rand(5, 4)
print("Original 5x4 Array:\n", rand_arr)

# 2.Row with the maximum sum of values
row_sums = np.sum(rand_arr, axis=1)
max_row_index = np.argmax(row_sums)

print("\nSums of each row:", row_sums)
print(f"Row with the maximum sum is Row {max_row_index} (Sum: {row_sums[max_row_index]:.4f})")

# 3. Normalize each row using the formula: (x - min) / (max - min)
#  calculate min and max along axis=1 (columns) and keep dimensions for broadcasting
row_min = np.min(rand_arr, axis=1, keepdims=True)
row_max = np.max(rand_arr, axis=1, keepdims=True)

normalized_arr = (rand_arr - row_min) / (row_max - row_min)
print("\nNormalized Array:\n", normalized_arr)

Original 5x4 Array:
 [[0.10010572 0.76948855 0.85772271 0.61061836]
 [0.57145559 0.78014303 0.26206626 0.39877257]
 [0.17867938 0.98800274 0.62162001 0.87907865]
 [0.40956399 0.0521102  0.8342215  0.3986754 ]
 [0.64491451 0.03114673 0.27649008 0.51482228]]

Sums of each row: [2.33793535 2.01243744 2.66738077 1.69457109 1.4673736 ]
Row with the maximum sum is Row 2 (Sum: 2.6674)

Normalized Array:
 [[0.         0.88353725 1.         0.67384001]
 [0.59718818 1.         0.         0.26387269]
 [0.         1.         0.54729747 0.86541338]
 [0.45703699 0.         1.         0.44311494]
 [1.         0.         0.39973319 0.78804325]]


In [5]:
import numpy as np

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

# Unique elements
unique_elements = np.unique(arr)

# Duplicates (elements that appear more than once)
elements, counts = np.unique(arr, return_counts=True)
duplicates = elements[counts > 1]

print("Unique elements:", unique_elements)
print("Duplicate elements:", duplicates)

Unique elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


In [6]:
import numpy as np

# 6x6 NumPy array with values from 1 to 36
matrix_6x6 = np.arange(1, 37).reshape(6, 6)

# Extract the middle 4x4 submatrix (slices rows 1 to 4 and columns 1 to 4)
middle_submatrix = matrix_6x6[1:5, 1:5]

# Even numbers from this submatrix
even_numbers = middle_submatrix[middle_submatrix % 2 == 0]

print("Original 6x6 Matrix:\n", matrix_6x6)
print("\nMiddle 4x4 Submatrix:\n", middle_submatrix)
print("\nEven numbers from submatrix:", even_numbers)

Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers from submatrix: [ 8 10 14 16 20 22 26 28]


In [ ]:
import numpy as np

# 1.Array of shape (3, 4) with values from 0 to 11
arr_3x4 = np.arange(12).reshape(3, 4)
print("Original (3,4) Array:\n", arr_3x4)

# 2. Reshape it to (2, 6)
arr_2x6 = arr_3x4.reshape(2, 6)
print("\nReshaped to (2,6):\n", arr_2x6)

# 3. Flatten it into a 1D array
arr_1d = arr_2x6.flatten()
print("\nFlattened to 1D Array:\n", arr_1d)

# 4. Convert the 1D array back to shape (4, 3)
arr_4x3 = arr_1d.reshape(4, 3)
print("\nConverted back to (4,3):\n", arr_4x3)

Original (3,4) Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened to 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Converted back to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
import numpy as np

# 1. Create the base array
a = np.array([[1, 2], [3, 4]])
print("Base Array 'a':\n", a)

# 2. Append a new row [5, 6]
# (axis=0 means adding horizontally along rows)
a_with_row = np.append(a, [[5, 6]], axis=0)
print("\nAfter appending row [5, 6]:\n", a_with_row)

# 3. Append a new column [7, 8, 9]
# (axis=1 adding vertically along columns. Reshape it to a column matrix (3,1))
new_column = np.array([7, 8, 9]).reshape(3, 1)
final_arr = np.append(a_with_row, new_column, axis=1)

print("\nAfter appending column [7, 8, 9]:\n", final_arr)

Base Array 'a':
 [[1 2]
 [3 4]]

After appending row [5, 6]:
 [[1 2]
 [3 4]
 [5 6]]

After appending column [7, 8, 9]:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [8]:
import numpy as np

# 1. Three starting arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# 2. Join them to form a single array
joined_arr = np.concatenate((a, b, c))
print("Joined 1D Array:\n", joined_arr)

# 3. Reshape the result into a 3x3 matrix
matrix_3x3 = joined_arr.reshape(3, 3)
print("\nReshaped 3x3 Matrix:\n", matrix_3x3)

# 4. Extract the diagonal elements
diagonal_elements = np.diag(matrix_3x3)
print("\nDiagonal Elements:\n", diagonal_elements)

Joined 1D Array:
 [1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements:
 [1 5 9]


In [9]:
import numpy as np

# 1.NumPy array of integers from 1 to 20
arr_1to20 = np.arange(1, 21)
print("Original Array:\n", arr_1to20)

# 2. Extract all values that are divisible by 3 or 5
#  use the '|' operator for the logical 'OR' condition
filtered_values = arr_1to20[(arr_1to20 % 3 == 0) | (arr_1to20 % 5 == 0)]
print("\nValues divisible by 3 or 5:\n", filtered_values)

# 3. Count how many such values exist
count_values = len(filtered_values)
print(f"\nNumber of values found: {count_values}")

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Number of values found: 9
